### ISSUE TITLE
CSS style-guide generator

### ISSUE THREAD

**Issue by sunny** [sunny/dev-ideas#32]
A JavaScript library that would allow this page:

``` html
<!doctype html>
<link rel="stylesheet" href="application.css">
<script src="css-style-guide.js"></script>
```

To render a full CSS style-guide, by showing all CSS and what the applied CSS looks like. Also shows comments before and after each CSS block.

To know what HTML to generate it would guess from the selector (`ul.important` would make an `<ul class="important">`) and rely on the examples in the CSS comments. For example:

``` css
/* Notes with stars
Example:
   <ul class="notation">
     <li>✭</li>
     <li>✭</li>
     <li>✭</li>
   </ul>
*/
.notation > * {
  color: yellow;
}
```
